### ISSUE TITLE
Go native function panics invoked from Javascript panic the Go runtime

### ISSUE THREAD

**Issue by jsccast** [Comcast/plax#106]
Example:

```yaml
spec:
  phases:
    phase1:
      steps:
        - run: |
            redactRegexp("[}")
```

The Go runtime because `redactRegexp()` [panics with a value that's not a Goja Value](https://github.com/dop251/goja#exceptions). The result should be "broken" test, not a Go runtime panic.
