### ISSUE TITLE
Zero string value for X_ parameter results in crazy-bad redactions

### ISSUE THREAD

**Issue by jsccast** [Comcast/plax#141]
See below for an example.

Should check that a `X_` parameter value is not the empty string before using it for redactions.

```YAML
bindings:
  '?X_OOPS': ''
spec:
  phases:
    phase1:
      steps:
        - pub:
            payload:
              make:
                name: mock
                type: mock
        - recv:
            chan: mother
            pattern:
              success: true
        - pub:
            payload: '42'
        - recv:
            pattern: '"?x"'
```

```
2021/10/29 14:13:12.440930 <redacted>|<redacted> <redacted> <redacted> <redacted> <redacted> <redacted> <redacted> <redacted>t<redacted>.<redacted>B<redacted>i<redacted>n<redacted>d<redacted>i<redacted>n<redacted>g<redacted>s<redacted>:<redacted> <redacted>{<redacted>"<redacted>?<redacted>X<redacted>_<redacted>O<redacted>O<redacted>P<redacted>S<redacted>"<redacted>:<redacted>"<redacted>"<redacted>,<redacted>"<redacted>?<redacted>x<redacted>"<redacted>:<redacted>4<redacted>2<redacted>}<redacted>
```
