### ISSUE TITLE
Support a "close" operation

### ISSUE THREAD

**Issue by jsccast** [Comcast/plax#154]
Every channel has an underlying "Close" method that is called automatically when a test terminates. This feature is asking to expose `close` as an operation that can be invoked from a test.

```YAML
spec:
  phases:
    phase1:
      steps:
        - pub:
            payload:
              make:
                name: mock
                type: mock
        - recv:
            chan: mother
            pattern:
              success: true
        - close:
            chan: mock
```
