### ISSUE TITLE
Expanding functionality for Octane Plugin

### ISSUE THREAD

**Issue by rkehl27** [Comcast/plax#157]
Add additional tagging and functionality to the Octane plugin to support passing in environment variable for indexing. The Environment section of the Octane report has many different potential fields including AUT Env, Browser, DB, Distribution, OS and custom values.  

Current configuration: 
```
reports:
  octane:
    config:
      host_url: "https://almoctane-ams.saas.microfocus.com"
      client_id: "{OCTANE_CLIENT_ID}"
      client_secret: "{OCTANE_CLIENT_SECRET}"
      shared_space_id: "{SHARED_SPACE_ID}"
      workspace_id: "{WORKSPACE_ID}"
      app_module_id: 485024
      test_fields:     // optional
        Framework: plax
```

Proposed Addition:
```
reports:
  octane:
    config:
      host_url: "https://almoctane-ams.saas.microfocus.com"
      client_id: "{OCTANE_CLIENT_ID}"
      client_secret: "{OCTANE_CLIENT_SECRET}"
      shared_space_id: "{SHARED_SPACE_ID}"
      workspace_id: "{WORKSPACE_ID}"
      app_module_id: 485024
      environment: // optional
         AUT_Env: {ENVIRONMENT}
      test_fields:     // optional
        Framework: plax
```
