### ISSUE TITLE
Deep @@FILENAME expansion fails

### ISSUE THREAD

**Issue by jsccast** [Comcast/plax#24]
Example:

```yaml
pub:
  payload:
    body: "@@foo.json"
```

The `@@FILENAME` substitution isn't performed.
