### ISSUE TITLE
Support reading multi-line ("pretty") JSON from a cmd

### ISSUE THREAD

**Issue by jsccast** [Comcast/plax#27]
Need some option to enable a `cmd` to receive a single multi-line blob of JSON.  Example use: AWS CLI, which seems to insist on emitting pretty JSON.

Example work-around:

```yaml
spec:
  phases:
    phase1:
      steps:
        - pub:
            payload:
              make:
                name: awscli
                type: cmd
                config:
                  command: bash
                  doc: |
                    The AWS CLI insists on "pretty" JSON, which we
                    don't want.  Here's a work-around using 'jq'.
                  args:
                    - '-c'
                    - 'aws iot describe-endpoint | jq -c' 
        - recv:
            chan: mother
            pattern:
              success: true
        - recv:
            chan: awscli
            pattern:
              endpointAddress: "?addr"
```
