### ISSUE TITLE
Plaxrun iteration over a map of parameters marshals values

### ISSUE THREAD

**Issue by jsccast** [Comcast/plax#74]
Example:

```Shell
plaxrun -run demos/iterate.yaml -dir demos -g iterate-v1 -log debug
plaxrun -run demos/iterate.yaml -dir demos -g iterate-v2 -log debug
```

with

```YAML
name: iterate
tests:
  basic:
    path: iterate-test.yaml

groups:
  iterate-v1:
    tests:
      - name: basic
    iterate:
      params: |
        [{"WANT":"tacos"},{"WANT":"chips"}]
  iterate-v2:
    tests:
      - name: basic
    iterate:
      param: "WANT"
      params: |
        ["tacos","chips"]
```

and

```YAML
spec:
  phases:
    phase1:
      steps:
        - pub:
            payload:
              make:
                name: mock
                type: mock
        - recv:
            chan: mother
            pattern:
              success: true
        - pub:
            payload: '{"want":"?WANT"}'
        - recv:
            pattern: '{"want":"?x"}'
            timeout: 1s
            guard: |
              return bs["?x"] == bs["?WANT"] && bs["?x"].substring(0,1) != '"'

```

`iterate-v2` does what I want: it iterates with values `tacos` (string) and `chips` (string), but `iterate-v1` iterates with `"tacos"` (with embedded quotes) and `"chips"` (with embedded quotes). I _think_ the behavior should be the same, and I _think_ it should be `iterate-v2`'s behavior. ?
